In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_json("article_metadata.json")

In [4]:
df.head()

,num_characters,num_words,num_sentences,avg_sentence_length,num_capitalized_words,num_exclamations,num_questions,has_clickbait_words,readability_score,sentiment_polarity,sentiment_subjectivity,pos_ratios,id,subject,class,date
0,2893,450,30,15.00,2,6,9,False,62.68,0.082132,0.599895,"{'PROPN': 0.2, 'ADV': 0.06, 'VERB': 0.12, 'DET...",0,News,Fake,"December 31, 2017"
1,1898,310,15,20.67,3,0,0,False,45.86,-0.005004,0.334098,"{'PROPN': 0.197, 'AUX': 0.048, 'VERB': 0.097, ...",1,News,Fake,"December 31, 2017"
2,3597,533,31,17.19,33,2,4,True,63.59,-0.012345,0.541969,"{'ADP': 0.099, 'PROPN': 0.152, 'PRON': 0.129, ...",2,News,Fake,"December 30, 2017"
3,2774,411,23,17.87,5,0,1,False,53.61,-0.023118,0.394086,"{'ADP': 0.095, 'PROPN': 0.131, 'NOUN': 0.202, ...",3,News,Fake,"December 29, 2017"
4,2346,422,20,21.10,0,0,0,False,58.62,-0.011722,0.495222,"{'PROPN': 0.109, 'VERB': 0.156, 'PRON': 0.1, '...",4,News,Fake,"December 25, 2017"

In [11]:
df["PROPN"] = df["pos_ratios"].apply(lambda x: x.get("PROPN", 0))
df["ADV"] = df["pos_ratios"].apply(lambda x: x.get("ADV", 0))
df["VERB"] = df["pos_ratios"].apply(lambda x: x.get("VERB", 0))
df["DET"] = df["pos_ratios"].apply(lambda x: x.get("DET", 0))
df["CCONJ"] = df["pos_ratios"].apply(lambda x: x.get("CCONJ", 0))
df["PRON"] = df["pos_ratios"].apply(lambda x: x.get("PRON", 0))
df["ADP"] = df["pos_ratios"].apply(lambda x: x.get("ADP", 0))
df["PART"] = df["pos_ratios"].apply(lambda x: x.get("PART", 0))
df["NOUN"] = df["pos_ratios"].apply(lambda x: x.get("NOUN", 0))
df["ADJ"] = df["pos_ratios"].apply(lambda x: x.get("ADJ", 0))
df["NUM"] = df["pos_ratios"].apply(lambda x: x.get("NUM", 0))
df["SCONJ"] = df["pos_ratios"].apply(lambda x: x.get("SCONJ", 0))
df["AUX"] = df["pos_ratios"].apply(lambda x: x.get("AUX", 0))

df = df.drop(["pos_ratios"], axis=1)

In [12]:
df.head()

,num_characters,num_words,num_sentences,avg_sentence_length,num_capitalized_words,num_exclamations,num_questions,has_clickbait_words,readability_score,sentiment_polarity,...,DET,CCONJ,PRON,ADP,PART,NOUN,ADJ,NUM,SCONJ,AUX
0,2893,450,30,15.00,2,6,9,False,62.68,0.082132,...,0.067,0.033,0.111,0.073,0.031,0.158,0.078,0.004,0.018,0.047
1,1898,310,15,20.67,3,0,0,False,45.86,-0.005004,...,0.094,0.026,0.048,0.129,0.016,0.184,0.090,0.010,0.029,0.048
2,3597,533,31,17.19,33,2,4,True,63.59,-0.012345,...,0.060,0.017,0.129,0.099,0.039,0.186,0.058,0.002,0.026,0.049
3,2774,411,23,17.87,5,0,1,False,53.61,-0.023118,...,0.100,0.027,0.071,0.095,0.036,0.202,0.044,0.000,0.024,0.080
4,2346,422,20,21.10,0,0,0,False,58.62,-0.011722,...,0.092,0.040,0.100,0.137,0.059,0.164,0.045,0.005,0.021,0.045

In [16]:
df.to_csv('final.csv')